#!/usr/bin/env python3
from whatsapp import Whatsapp,Message,WhatsappOptions
from time import sleep
from configparser import ConfigParser
from typing import NoReturn,List,Callable,Dict,Any,Optional,IO
from telegram.ext import Updater, CommandHandler, MessageHandler
from telegram.ext.dispatcher import Dispatcher
from telegram.ext.callbackcontext import CallbackContext
from telegram.update import Update
from os.path import join,exists
from telegram.bot import Bot
from io import BytesIO,StringIO
from json import dump,load
from telegram.ext.filters import Filters
from argparse import ArgumentParser,Namespace
from logging import DEBUG,getLogger,Logger,basicConfig,INFO,ERROR
from sys import stdout
DATA_DIR:str='data'
DATA_FILE:str=join(DATA_DIR,'data.json')

USERNAME='username'
DEFAULT_CHAT_ID='default_chat_id'
ASSOCIATIONS='associations'
DEFAULT_CHAT='default_chat'

AUTH_FILE='auth.ini'
TELEGRAM_SECTION='telegram'
TELEGRAM_TOKEN='token'
ADMIN='admin'

USERS='users'

users:List['User']=[]
current_mode:Optional[Callable[[Update,'User'],NoReturn]]=None
options:WhatsappOptions=WhatsappOptions()
logger:Logger=getLogger(__name__)
logs:StringIO=StringIO()
admin:str=''

class JoinStream:
    def __init__(self,stream1,stream2):
        self.stream1=stream1
        self.stream2=stream2

    def write(self,message):
        self.stream1.write(message)
        self.stream2.write(message)

    def flush(self):
        self.stream1.flush()
        self.stream2.flush()

stream:JoinStream=JoinStream(stdout,logs)
stream:IO[str]
basicConfig(level=ERROR,stream=stream)

class User:
    def __init__(self,bot:Bot,username:str,default_chat_id:int,associations:Dict[str,int]=None,default_chat:str=None):
        self.bot:Bot=bot
        self.username:str=username
        self.default_chat_id:int=default_chat_id
        self._default_chat:Optional[str]=default_chat
        self.associations:Dict[str,int]={} if associations is None else associations
        self.whatsapp=Whatsapp(join(DATA_DIR, username),options)
        self.whatsapp.qr_callback = self._create_callback()

    def _set_default_chat(self,default_chat:str)->NoReturn:
        if not self.whatsapp.user_exists(default_chat):
            raise WhatsappUserNotFoundError(default_chat)
        self._default_chat=default_chat

    default_chat:Optional[str]=property(lambda self:self._default_chat,_set_default_chat)

    def _create_callback(self)->Callable[[bytes],NoReturn]:
        def method(image:bytes):
            self.bot.send_photo(self.default_chat_id,BytesIO(image))
        return method

    def add_association(self,who:str,chat:int)->NoReturn:
        if not self.whatsapp.user_exists(who):
            raise WhatsappUserNotFoundError(who)
        self.associations[who]=chat

    def receive_messages(self):
        if not self.whatsapp.logged_in:
            return
        messages:List[Message]=self.whatsapp.get_unread_messages()
        if len(messages)>0:
            logger.debug(f'User {self.username} has received {len(messages)} message/es')
        for message in messages:
            text:str=''
            chat_id:int=self.default_chat_id
            if message.sender not in self.associations:
                text=f'{message.sender}: '
            else:
                chat_id=self.associations[message.sender]
            self.bot.send_message(chat_id,text+message.message)
        if len(messages)>0 and self.default_chat is not None:
            self.whatsapp.select_chat(self.default_chat)

    def send_message(self,chat_id:int,message:str):
        who:Optional[str]=None
        for key in self.associations.keys():
            if self.associations[key]==chat_id:
                who=key
        if who is None:
            who=message.split(' ')[0]
            message=message[len(who)+1:]
        logger.debug(f'User {self.username} sent a message to {who}')
        self.whatsapp.send_message(who,message)
        if self.default_chat is not None:
            self.whatsapp.select_chat(self.default_chat)

    def as_dict(self)->Dict[str,Any]:
        return {USERNAME:self.username,DEFAULT_CHAT_ID:self.default_chat_id,
                ASSOCIATIONS:self.associations,DEFAULT_CHAT:self.default_chat}

    def __repr__(self)->str:
        data:Dict[str,Any]=self.as_dict()
        del data[DEFAULT_CHAT]
        del data[ASSOCIATIONS]
        return str(data)

    def log(self,message:str):
        self.bot.send_message(self.default_chat_id,message)


def main()->NoReturn:
    global admin
    parser:ArgumentParser=ArgumentParser()
    parser.add_argument('-s','--show',action='store_true',default=False,help='Shows the chrome window')
    parser.add_argument('-i','--interactive',action='store_true',default=False,
                        help='Make the chrome window a normal window')
    parser.add_argument('-b','--block-sending',action='store_true',help='Block message sending for debug')
    parser.add_argument('-d','--debug',action='store_true',help='Starts the server in debug mode')
    args:Namespace=parser.parse_args()
    options.show=args.show
    options.interactive = args.interactive
    options.block=args.block_sending
    options.debug=args.debug
    logger.setLevel(DEBUG if options.debug else INFO)

    config=ConfigParser()
    config.read(AUTH_FILE)
    if TELEGRAM_SECTION not in config:
        raise Exception('Missing or malformed auth.ini')
    admin = config[TELEGRAM_SECTION][ADMIN]

    updater:Updater=Updater(config[TELEGRAM_SECTION][TELEGRAM_TOKEN],use_context=True)
    restore_all(updater.bot)
    dispatcher:Dispatcher=updater.dispatcher
    dispatcher.add_handler(CommandHandler('start',start))
    dispatcher.add_handler(CommandHandler('stop',stop))
    dispatcher.add_handler(CommandHandler('logs',show_logs))
    dispatcher.add_handler(CommandHandler('screenshot',take_screenshot))
    dispatcher.add_handler(CommandHandler('associate',create_set_mode(associate)))
    dispatcher.add_handler(CommandHandler('set_default_chat',create_set_mode(set_default_chat)))
    dispatcher.add_handler(MessageHandler(Filters.text & ~Filters.command,on_message))
    updater.start_polling()
    try:
        logger.info('Started')
        logger.debug('Debug Mode On')
        notify_all('The bot is online')
        while True:
            for user in users:
                user.receive_messages()
            sleep(3)
    finally:
        logger.info('Shutting down')
        notify_all('The bot is shutting down')
        updater.stop()
        save_all()

def start(update:Update,context:CallbackContext)->NoReturn:
    username:str=update.message.from_user.username
    chat_id:int=update.message.chat_id
    log('start',username=username,chat_id=chat_id)
    update.message.reply_text(f'Your username is {username} with chat id {chat_id}')
    user:User=User(context.bot,username,chat_id)

    def logged_in():
        user.log('Log in successful')

    user.whatsapp.logged_in_callback=logged_in
    users.append(user)

def associate(update:Update,user:User):
    try:
        who:str=update.message.text
        chat_id:int=update.message.chat_id
        user.add_association(who,chat_id)
        log('associate',user=user,who=who,chat_id=chat_id)
        update.message.reply_text('The association was successful')
    except WhatsappUserNotFoundError as e:
        e.log_error(update)

def stop(update:Update,_context:CallbackContext):
    try:
        user:User=find_user(update.message.from_user.username)
        log('stop',user=user)
        user.whatsapp.close()
        users.remove(user)
        update.message.reply_text('Stopped')
    except NoSuchUserError as e:
        e.log_error(update)

def show_logs(update:Update,_context:CallbackContext):
    try:
        username:str=update.message.from_user.username
        log('logs',username=username)
        if username==admin:
            update.message.reply_text(logs.getvalue())
        else:
            update.message.reply_text('You are not authorized for this command')
    except NoSuchUserError as e:
        e.log_error(update)

def take_screenshot(update:Update,_context:CallbackContext):
    try:
        user:User=find_user(update.message.from_user.username)
        log('screenshot',user=user)
        update.message.reply_photo(BytesIO(user.whatsapp.driver.get_screenshot_as_png()))
    except NoSuchUserError as e:
        e.log_error(update)

def set_default_chat(update:Update,user:User):
    try:
        default_chat:str=update.message.text
        user.default_chat=default_chat
        log('set_default_chat',default_chat=default_chat)
        update.message.reply_text('Default chat successfully changed')
    except NoSuchUserError as e:
        e.log_error(update)

def on_message(update:Update,_context:CallbackContext)->NoReturn:
    global current_mode
    try:
        user:User=find_user(update.message.from_user.username)
        if current_mode is not None:
            current_mode(update,user)
            current_mode=None
        else:
            user.send_message(update.message.chat_id,update.message.text)
    except NoSuchUserError as e:
        e.log_error(update)

def save_all():
    with open(DATA_FILE,'w') as f:
        dump({USERS:[user.as_dict() for user in users]},f)

def restore_all(bot:Bot):
    if not exists(DATA_FILE):
        return
    with open(DATA_FILE,'r') as f:
        data:Dict[str,Any]=load(f)
        for user in data[USERS]:
            users.append(User(bot,user[USERNAME],user[DEFAULT_CHAT_ID],user[ASSOCIATIONS],user[DEFAULT_CHAT]))

def notify_all(message:str):
    for user in users:
        user.log(message)

def create_set_mode(mode:Callable[[Update,User],NoReturn])->Callable[[Update,CallbackContext],NoReturn]:
    def method(_update:Update,_context:CallbackContext):
        global current_mode
        current_mode=mode
    return method

def find_user(username:str)->User:
    for user in users:
        if user.username==username:
            return user
    raise NoSuchUserError(username)

class NoSuchUserError(Exception):
    def __init__(self,username:str):
        self.username:str=username
        super(NoSuchUserError, self).__init__(f'User {username} not found')

    def log_error(self,update:Update):
        logger.error(str(self),exc_info=True)
        update.message.reply_text(f'User {self.username} not found, have you logged in with /start?')

class WhatsappUserNotFoundError(Exception):
    def __init__(self,username:str):
        self.username:str=username
        super(WhatsappUserNotFoundError, self).__init__(f'Whatsapp user {username} not found')

    def log_error(self,update:Update):
        logger.error(str(self), exc_info=True)
        update.message.reply_text(f'Whatsapp user {self.username} not found, is it right?')

def log(command:str,**kwargs):
    message:str=f'/{command}'
    for key in kwargs.keys():
        message+=f' {key}={kwargs[key]}'
    logger.info(message)

if __name__ == '__main__':
    main()
