#!/usr/bin/env python3
from whatsapp import WhatsappOptions
from typing import NoReturn,Dict,Any
from argparse import ArgumentParser,Namespace
from whatsappwebbot import WhatsappWebBot
from sys import stdout
from os import environ,makedirs,getuid
from os.path import expanduser,join,exists
from yaml import safe_load

TELEGRAM_TOKEN='token'
TELEGRAM_TEST_TOKEN='test-token'
ADMIN='admin'
USER_CONFIG_DIR_VARIABLE='XDG_CONFIG_HOME'
USER_CONFIG_DIR=join(expanduser('~'),'.config','whatsappwebbot') if USER_CONFIG_DIR_VARIABLE not in environ else \
    environ[USER_CONFIG_DIR_VARIABLE]
ROOT_CONFIG_DIR=join('/','etc','whatsappwebbot')
DEFAULT_DATA_DIR=ROOT_CONFIG_DIR if getuid()==0 else USER_CONFIG_DIR
DEFAULT_AUTH_FILE=join(DEFAULT_DATA_DIR,'auth.yml')

def main()->NoReturn:
    parser:ArgumentParser=ArgumentParser()
    parser.add_argument('-s','--show',action='store_true',default=False,help='Shows the chrome window')
    parser.add_argument('-i','--interactive',action='store_true',default=False,
                        help='Make the chrome window a normal window')
    parser.add_argument('-d','--debug',action='store_true',default=False,help='Starts the server in debug mode')
    parser.add_argument('-t', '--test-bot', action='store_true',default=False,help='Starts the server with the tet bot')
    parser.add_argument('--silent-start',action='store_true',default=False,
                        help='Start the server without notifying the users')
    parser.add_argument('--auth-file',type=str,default=DEFAULT_AUTH_FILE,help='The file to read the configuration from')
    parser.add_argument('--data-dir',type=str,default=DEFAULT_DATA_DIR,help='The directory to use to store the data')
    args:Namespace=parser.parse_args()
    options: WhatsappOptions = WhatsappOptions()
    options.show=args.show
    options.interactive = args.interactive
    options.debug=args.debug

    if not exists(args.data_dir):
        makedirs(args.data_dir)
    if not exists(args.auth_file):
        with open(args.auth_file,'wt') as f:
            f.write('token: \nadmin: ')
        print(f'You can now insert your telegram bot token in {args.auth_file}')
        exit(0)
    with open(args.auth_file,'rt') as f:
        config:Dict[str,Any]=safe_load(f.read())
    admin:int = config[ADMIN]
    token:str = config[TELEGRAM_TEST_TOKEN] if args.test_bot else config[TELEGRAM_TOKEN]
    WhatsappWebBot(options,token,args.data_dir,admin,stdout,args.silent_start).start()

if __name__ == '__main__':
    main()
